=== Alexey-Kuznecov/ProgramManager/ProgramManager/Resources/User/packages.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio Developer Edition 9.0.11.3078 (http://www.liquid-technologies.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Packages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Package" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="1">
                            <xs:element name="Author" type="xs:string" />
                            <xs:element name="CompanySite" type="URL" minOccurs="0" />
                            <xs:element name="Copyright" type="xs:string" minOccurs="0" />
                            <xs:element name="Description" type="xs:string" minOccurs="0" />
                            <xs:element name="HashSumm" type="xs:string" minOccurs="0" />
                            <xs:element name="License" type="xs:string" minOccurs="0" />
                            <xs:element name="Image" type="ImageAttributes" minOccurs="0" />
                            <xs:element name="Name" type="xs:string" />
                            <xs:element name="SerialKey" type="xs:string" minOccurs="0" />
                            <xs:element name="Source" type="URL" minOccurs="0" />
                            <xs:group ref="TagGroup" />
                            <xs:group minOccurs="0" ref="UserfieldGroup" />
                            <xs:element name="Version" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                        <xs:attribute name="Id" type="Id" />
                        <xs:attribute name="Category" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--ОБЪЯВЛЕНИЯ АТРИБУТОВ-->
    <xs:complexType name="UserfieldAttributes">
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="Label" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ImageAttributes">
        <xs:attribute name="Source" type="ImagePath" use="required"/>
    </xs:complexType>
    <!--ТЕГИ-->
    <xs:group name="TagGroup">
        <xs:choice>
            <xs:element name="Tag" type="xs:string" />
            <xs:element name="TagList">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Tag" type="xs:string" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <!--ПОЛЬЗОВАТЕЛЬСКИЕ ПОЛЯ-->
    <xs:group name="UserfieldGroup">
        <xs:choice>
          <xs:element name="Userfield" type="UserfieldAttributes"/>
            <xs:element name="UserfieldList">
                <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Userfield" maxOccurs="unbounded" type="UserfieldAttributes"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <!--ОПРЕДЕЛЕНИЯ ПРОСТЫХ ТИПОВ-->
    <xs:simpleType name="Id">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="3000" />
            <xs:minExclusive value="-1" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="URL">
        <xs:restriction base="xs:string">
            <xs:pattern value="http[s]?://[w]+\.\w+\.(com|ru|org|net)/?[-a-zA-Z0-9\#/?=]+" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ImagePath">
        <xs:restriction base="xs:string">
            <xs:pattern value="\.\./Resources/User/Images/[-a-zA-Z0-9\-_]+\.(jpg|png)" />
        </xs:restriction>
    </xs:simpleType>
    <!--<xs:simpleType name="Birthday">
    <xs:restriction base="xs:date">
      <xs:minInclusive value="1950-01-01" />
      <xs:maxInclusive value="2010-12-31" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="workDays">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Воскресение" />
      <xs:enumeration value="Понидельник" />
      <xs:enumeration value="Вторник" />
      <xs:enumeration value="Среда" />
      <xs:enumeration value="Четрверг" />
      <xs:enumeration value="Пятница" />
      <xs:enumeration value="Суббота" />
    </xs:restriction>
  </xs:simpleType>-->
</xs:schema>

=== Alexey-Kuznecov/ProgramManager/ProgramManager/Resources/User/packages.xml
<?xml version="1.0" encoding="utf-8"?>
<Packages xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="packages.xsd">
  <Package Id="0" Category="Программы">
    <Author>Adobe</Author>
    <CompanySite>https://www.Adobe.com/</CompanySite>
    <Description>Программа для оформления фотографий</Description>
    <License>5Q86W-TFPN7-K8VCJ-PH3CT</License>
    <Name>Photoshop</Name>
    <Tag>Не подшитые</Tag>
    <Version>Cloud CC6</Version>
  </Package>
  <Package Id="1" Category="Программы">
    <Author>Adobe</Author>
    <Description>Программа для оформления фотографий</Description>
    <Name>Illustrator</Name>
    <Tag>Офисные</Tag>
    <Version>Cloud CC6</Version>
  </Package>
  <Package Id="2" Category="Программы">
    <Author>Axure Software Solution</Author>
    <Description>Программа для создания прототипов сайтов</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Axure</Name>
    <Tag>Инструменты вебразработчика</Tag>
    <Version>RP 8</Version>
  </Package>
  <Package Id="3" Category="Программы">
    <Author>Andrei Kulabukhau</Author>
    <Description>Программа для измерения времени</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>LazyCure</Name>
    <Tag>Органазеры</Tag>
    <Version>0.10</Version>
  </Package>
  <Package Id="4" Category="Программы">
    <Author>Mozilla</Author>
    <Description>Программа для просмотра вебстраниц</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Firefox</Name>
    <Tag>Браузеры</Tag>
    <Version>7.9.4</Version>
  </Package>
  <Package Id="5" Category="Программы">
    <Author>Google</Author>
    <Description>Программа для просмотра вебстраниц</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Chrome</Name>
    <Tag>Браузеры</Tag>
    <Version>8.5.0</Version>
  </Package>
  <Package Id="6" Category="Программы">
    <Author>Microsoft</Author>
    <Description>Программа для организации электронных писем</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Microsoft Outlook</Name>
    <Tag>Офисные</Tag>
    <Version>2017</Version>
  </Package>
  <Package Id="7" Category="Программы">
    <Author>Microsoft</Author>
    <Description>Программа для написания, редактирования, оформления текста и многое другое.</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Microsoft Word</Name>
    <Tag>Офисные</Tag>
    <Version>2017</Version>
  </Package>
  <Package Id="8" Category="Программы">
    <Author>Piriform</Author>
    <Description>Программа очиски компьютора</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>CCleaner</Name>
    <Tag>Оптимизатры</Tag>
    <Version>5.43.6520</Version>
  </Package>
  <Package Id="9" Category="Программы">
    <Author>ChemTable Software</Author>
    <Description>Программа для оптимизации, отчиски, дефрагментации реестра и многое другое</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Reg Organizer</Name>
    <Tag>Оптимизатры</Tag>
    <Version>8.16</Version>
  </Package>
  <Package Id="10" Category="Программы">
    <Author>Неизвестно</Author>
    <Description>Программа организации задач</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>LeaderTask</Name>
    <Tag>Органазеры</Tag>
    <Version>6.0</Version>
  </Package>
  <Package Id="11" Category="Программы">
    <Author>Kasperski Lab</Author>
    <Description>Программа для защиты компютера от вирусов</Description>
    <Name>Kasperski</Name>
    <Tag>Антивирусы</Tag>
    <Version>6.0</Version>
  </Package>
  <Package Id="12" Category="Программы">
    <Author>HQ Pty Ltd</Author>
    <Description>Многофункциональный редактор кода</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Sublime Text 3</Name>
    <TagList>
      <Tag>Редакторы кода</Tag>
      <Tag>Инструменты вебразработчика</Tag>
    </TagList>
    <Version>3.1.1 Build 3176</Version>
  </Package>
  <Package Id="13" Category="Программы">
    <Author>Notepad++Team</Author>
    <Description>Удобный и мультифункциональный редактор кода</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Notepad++</Name>
    <Tag>Редакторы кода</Tag>
    <Version>7.4.2</Version>
  </Package>
  <Package Id="14" Category="Программы">
    <Author>Microsoft</Author>
    <Description>Интегрированая среда разработки</Description>
    <Name>Microsoft Visual Studio</Name>
    <Tag>Не подшитые</Tag>
    <Version>14.0</Version>
  </Package>
  <Package Id="15" Category="Программы">
    <Author>Poligonic</Author>
    <Description>Программа для создания 3D моделей</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Zbrush</Name>
    <Tag>3D Редакторы</Tag>
    <Version>10</Version>
  </Package>
  <Package Id="16" Category="Программы">
    <Author>NetBeans Software</Author>
    <Description>Интегрированая среда разработки</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>NetBeans</Name>
    <Tag>IDE</Tag>
    <Version>9.1.0</Version>
  </Package>
  <Package Id="17" Category="Программы">
    <Author>Discord Team</Author>
    <Description>Программа для создания сообществ</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Discord</Name>
    <Tag>Меседжеры</Tag>
    <Version>3.0</Version>
  </Package>
  <Package Id="18" Category="Программы">
    <Author>Slack Team</Author>
    <Description>Программа для создания сообществ</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Slack</Name>
    <Tag>Меседжеры</Tag>
    <Version>2.2</Version>
  </Package>
  <Package Id="19" Category="Игры">
    <Author>CD Project Red</Author>
    <Description>Игра для романтиков на досуге мясников</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>The Witcher 3 Wild Hunt</Name>
    <Tag>RPG</Tag>
    <Version>3.31</Version>
  </Package>
  <Package Id="20" Category="Игры">
    <Author>Mod Doc Software</Author>
    <CheatCode>dasdsa</CheatCode>
    <Description>Игра для настоящих царей</Description>
    <Name>Empire Earth 2</Name>
    <Tag>Не подшитые</Tag>
    <Version>2.2</Version>
  </Package>
  <Package Id="21" Category="Драйвера">
    <Author>Realtek</Author>
    <Image Source="User/Images/19572.jpg" />
    <Name>High Definition Audio</Name>
    <Tag>Звуковая карта</Tag>
    <Version>3.31</Version>
  </Package>
  <Package Id="22" Category="Драйвера">
    <Author>Logitech</Author>
    <Image Source="User/Images/19572.jpg" />
    <Name>Logitech HD Webcam C270</Name>
    <Tag>Аксессуары</Tag>
    <Version>2.2</Version>
  </Package>
  <Package Id="24" Category="Моды">
    <Author>Logitech</Author>
    <Description>Качественный мод для 3 Ведьмака, который улучшит качество графики в игре.</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>1.000 Times Better 2.3.1</Name>
    <Tag>Реворк</Tag>
    <Version>2.3.1</Version>
  </Package>
  <Package Id="25" Category="Игры">
    <Author>Valve</Author>
    <Description>Игра для настоящих ассов</Description>
    <Image Source="User/Images/19572.jpg" />
    <Name>Counter Strike GO</Name>
    <Tag>Shooter</Tag>
    <Version>2.2</Version>
  </Package>
  <Package Id="26" Category="Программы">
    <Author>Mindjet</Author>
    <CompanySite>https://www.mindjet.com/ru/</CompanySite>
    <Description>MindManager — самая мощная в мире программа.</Description>
    <Name>MindManager</Name>
    <Tag>Органазеры</Tag>
    <Userfield Label="Лозунг">Распознавайте.  Объединяйте.  Стимулируйте.</Userfield>
    <Version>7.7.0</Version>
  </Package>
  <Package Id="27" Category="Программы">
    <Author>Liquid Technogies Limited</Author>
    <Description>Среда разработки XML проектов.</Description>
    <License>EMBRACED XXXXXXX</License>
    <Name>XML Studio Developer</Name>
    <Tag>IDE</Tag>
    <Userfield Label="Лозунг">Build on 28.02.2011 (Build No : 3078)</Userfield>
    <Version>9.0.11.3078</Version>
  </Package>
  <Package Id="28" Category="Драйвера">
    <Author>фывфыв</Author>
    <Description>фывфыв</Description>
    <Name>фвфыф</Name>
    <Tag>Не подшитые</Tag>
    <Version>фывфывф</Version>
  </Package>
</Packages>
